### ISSUE TITLE
my opinion

### ISSUE THREAD

**Issue by WhiteHyun** [jang010505/DataStruct_HW1#1]
## ATM_SIZE

- 매크로 ATM_SIZE가 선언되어있는데
  https://github.com/jang010505/DataStruct_HW1/blob/088b97ef0caf6c175100646dfcc6fe788d92f5a4/main.c#L9

---

- 여러 줄에서는 그냥 3이라고만 써놓으셨어요!

  https://github.com/jang010505/DataStruct_HW1/blob/088b97ef0caf6c175100646dfcc6fe788d92f5a4/main.c#L18

  > 제가 알기로는 define은 상수취급되기 때문에 배열선언할 때 넣어도 되는 걸로 알고있어요.

https://github.com/jang010505/DataStruct_HW1/blob/088b97ef0caf6c175100646dfcc6fe788d92f5a4/main.c#L22

---

## IsEmpty 사용

- IsEmpty 선언문
  https://github.com/jang010505/DataStruct_HW1/blob/9cfa99e56858ff6783a47646679cc66a909d7e26/Deque.c#L9-L10

- 이거 대신에
  https://github.com/jang010505/DataStruct_HW1/blob/088b97ef0caf6c175100646dfcc6fe788d92f5a4/main.c#L41

- 이렇게 하는 것도 나쁘지 않을 거 같아요
  ```c
  if(!IsEmpty(&dq[i]))
  ```

## P.S

- 코딩괴물.. 이걸 2시간만에 해내다니..!👀

**Comment by jang010505** [comment]
오호호 감사합니당 >_<
